/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author bay
 */

import javax.swing.JOptionPane;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import javax.swing.JButton;
public class dashboard extends javax.swing.JFrame {
    double saldo;
    // ArrayList untuk menyimpan riwayat transaksi (Fitur Mutasi)
    ArrayList<String> mutasiRekening = new ArrayList<>();

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(dashboard.class.getName());

    /**
     * Creates new form dashboard
     */
    public dashboard() {
        initComponents();
        this.saldo = 0;
        initComponents();
        this.setLocationRelativeTo(null);
        applyModernStyle();
    }

    // Konstruktor dengan parameter saldo dari Login
    public dashboard(double saldo) {
        this.saldo = saldo;
        initComponents();
        this.setLocationRelativeTo(null);
        // Mencatat saldo awal ke mutasi
        catatMutasi("Saldo Awal", saldo);
        updateDisplay();
        applyModernStyle();
    }

    private void applyModernStyle() {
        // Warna Background Putih Bersih
        this.getContentPane().setBackground(Color.WHITE);
        
        // Header Biru
        jPanelHeader.setBackground(new Color(20, 50, 90));
        jLabel1.setForeground(Color.WHITE);
        jLabelWelcome.setForeground(Color.WHITE);
        
        // Styling Saldo Panel (Kotak Biru Terang)
        jtxtTampilan2.setBackground(new Color(230, 240, 255));
        jtxtTampilan2.setForeground(new Color(20, 50, 90));
        jtxtTampilan2.setBorder(javax.swing.BorderFactory.createLineBorder(new Color(20, 50, 90), 2));
        
        // Styling Tombol (Memanggil fungsi styleButton di bawah)
        styleButton(btnSimpan, new Color(40, 167, 69)); // Hijau
        styleButton(btnTarik, new Color(220, 53, 69));  // Merah
        styleButton(btnTransfer, new Color(0, 123, 255)); // Biru
        styleButton(btnTopUp, new Color(111, 66, 193)); // Ungu
        styleButton(btnMutasi, new Color(23, 162, 184)); // Cyan
        styleButton(btnKurs, new Color(255, 193, 7)); // Kuning
        
        // Text Kurs perlu hitam agar terbaca di background kuning
        btnKurs.setForeground(Color.BLACK);
        
        styleButton(btnLogout, new Color(108, 117, 125)); // Abu
    }

    private void styleButton(JButton btn, Color color) {
        btn.setBackground(color);
        btn.setForeground(Color.WHITE);
        btn.setFont(new Font("Segoe UI", Font.BOLD, 12));
        btn.setBorderPainted(false);
        btn.setFocusPainted(false);
    }

    // Method untuk format tampilan uang Rupiah
    private void updateDisplay() {
        jtxtTampilan2.setText(String.format("Rp %,.2f", saldo));
    }

    // Fitur mencatat riwayat ke ArrayList
    private void catatMutasi(String jenis, double nominal) {
        String catatan = String.format("%s : Rp %,.2f", jenis, nominal);
        mutasiRekening.add(catatan);
    }

    // Helper method untuk meminta input angka yang aman
    private double getAmountInput(String message) {
        String input = JOptionPane.showInputDialog(rootPane, message);
        if (input == null || input.isEmpty()) return 0;
        try {
            return Double.parseDouble(input);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, "Input harus angka!", "Error", JOptionPane.ERROR_MESSAGE);
            return 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelHeader = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelWelcome = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtxtTampilan2 = new javax.swing.JTextField();
        btnSimpan = new javax.swing.JButton();
        btnTarik = new javax.swing.JButton();
        btnTransfer = new javax.swing.JButton();
        btnTopUp = new javax.swing.JButton();
        btnMutasi = new javax.swing.JButton();
        btnKurs = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Dashboard - Bank Makmur");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BANK MAKMUR");

        jLabelWelcome.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelWelcome.setText("Selamat Datang, Nasabah Yth.");

        javax.swing.GroupLayout jPanelHeaderLayout = new javax.swing.GroupLayout(jPanelHeader);
        jPanelHeader.setLayout(jPanelHeaderLayout);
        jPanelHeaderLayout.setHorizontalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelWelcome)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelHeaderLayout.setVerticalGroup(
            jPanelHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelHeaderLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelWelcome)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("Saldo Aktif");

        jtxtTampilan2.setEditable(false);
        jtxtTampilan2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jtxtTampilan2.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        jtxtTampilan2.setText("Rp 0,00");

        btnSimpan.setText("SETOR TUNAI");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnTarik.setText("TARIK TUNAI");
        btnTarik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTarikActionPerformed(evt);
            }
        });

        btnTransfer.setText("TRANSFER");
        btnTransfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTransferActionPerformed(evt);
            }
        });

        btnTopUp.setText("E-WALLET");
        btnTopUp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTopUpActionPerformed(evt);
            }
        });

        btnMutasi.setText("MUTASI REK");
        btnMutasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMutasiActionPerformed(evt);
            }
        });

        btnKurs.setText("CEK KURS USD");
        btnKurs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKursActionPerformed(evt);
            }
        });

        btnLogout.setText("LOGOUT");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2)
                    .addComponent(jtxtTampilan2)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnMutasi, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnTransfer, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSimpan, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnTarik, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
                            .addComponent(btnTopUp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnKurs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtTampilan2, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTarik, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransfer, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTopUp, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMutasi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnKurs, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 1. Setor Tunai
    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {                                          
        double masukan = getAmountInput("Masukan jumlah setor tunai :");
        if (masukan > 0) {
            saldo += masukan;
            catatMutasi("Setor Tunai", masukan); // Catat ke history
            updateDisplay();
            JOptionPane.showMessageDialog(rootPane, "Setor Tunai Berhasil!");
        }
    }

    // 2. Tarik Tunai
    private void btnTarikActionPerformed(java.awt.event.ActionEvent evt) {                                         
        double tarik = getAmountInput("Masukan jumlah tarik tunai :");
        if (tarik > 0) {
            if (saldo >= tarik) {
                saldo -= tarik;
                catatMutasi("Tarik Tunai", -tarik); // Catat (minus)
                updateDisplay();
                JOptionPane.showMessageDialog(rootPane, "Penarikan Berhasil.");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Saldo Kurang!", "Gagal", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    // 3. Transfer
    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {                                            
        String rekTujuan = JOptionPane.showInputDialog(rootPane, "Masukan Nomor Rekening Tujuan:");
        if (rekTujuan != null && !rekTujuan.isEmpty()) {
            double nominal = getAmountInput("Masukan nominal transfer :");
            if (nominal > 0) {
                if (saldo >= nominal) {
                    saldo -= nominal;
                    catatMutasi("Transfer ke " + rekTujuan, -nominal);
                    updateDisplay();
                    JOptionPane.showMessageDialog(rootPane, "Transfer Berhasil!");
                } else {
                    JOptionPane.showMessageDialog(rootPane, "Saldo Kurang!", "Gagal", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }

    // 4. TOP UP E-WALLET (NEW FEATURE)
    private void btnTopUpActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // Pilihan E-Wallet
        String[] options = {"GOPAY", "DANA", "OVO", "SHOPEEPAY"};
        int choice = JOptionPane.showOptionDialog(rootPane, "Pilih E-Wallet:", "Top Up",
                JOptionPane.DEFAULT_OPTION, JOptionPane.QUESTION_MESSAGE, null, options, options[0]);
        
        if (choice >= 0) { // Jika user memilih salah satu
            String walletName = options[choice];
            String nomorHP = JOptionPane.showInputDialog("Masukkan Nomor HP " + walletName + ":");
            
            if (nomorHP != null && !nomorHP.isEmpty()) {
                double nominal = getAmountInput("Jumlah Top Up:");
                if (nominal > 0) {
                    if (saldo >= nominal) {
                        saldo -= nominal;
                        catatMutasi("Top Up " + walletName, -nominal);
                        updateDisplay();
                        JOptionPane.showMessageDialog(rootPane, "Top Up " + walletName + " Berhasil!");
                    } else {
                        JOptionPane.showMessageDialog(rootPane, "Saldo Tidak Cukup!");
                    }
                }
            }
        }
    }

    // 5. LIHAT MUTASI (NEW FEATURE)
    private void btnMutasiActionPerformed(java.awt.event.ActionEvent evt) {                                          
        StringBuilder sb = new StringBuilder();
        sb.append("=== RIWAYAT TRANSAKSI ===\n\n");
        if (mutasiRekening.isEmpty()) {
            sb.append("(Belum ada transaksi)");
        } else {
            // Loop untuk mengambil data dari ArrayList
            for (String s : mutasiRekening) {
                sb.append(s).append("\n");
            }
        }
        JOptionPane.showMessageDialog(rootPane, sb.toString(), "Mutasi Rekening", JOptionPane.INFORMATION_MESSAGE);
    }

    // 6. CEK KURS DOLLAR (NEW FEATURE)
    private void btnKursActionPerformed(java.awt.event.ActionEvent evt) {                                        
        double kursUSD = 16250; // Anggap 1 USD = Rp 16.250
        double nilaiUSD = saldo / kursUSD;
        
        String pesan = String.format("Saldo Anda: Rp %,.2f\n\nEstimasi dalam USD:\n$ %,.2f", saldo, nilaiUSD);
        JOptionPane.showMessageDialog(rootPane, pesan, "Konversi Mata Uang", JOptionPane.INFORMATION_MESSAGE);
    }

    // 7. Logout - NEW FEATURE
    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {                                          
        int confirm = JOptionPane.showConfirmDialog(rootPane, "Yakin ingin Logout?", "Logout", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            new login().setVisible(true);
            this.dispose();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new dashboard().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKurs;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMutasi;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTarik;
    private javax.swing.JButton btnTopUp;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelWelcome;
    private javax.swing.JPanel jPanelHeader;
    private javax.swing.JTextField jtxtTampilan2;
    // End of variables declaration//GEN-END:variables
}
